/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author fanim
 */
public class CadastrarUsuario2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastrarUsuario2.class.getName());

    /**
     * Creates new form CadastrarUsuario2
     */
    public CadastrarUsuario2() {
        initComponents();
    }
    
    public CadastrarUsuario2{
    
        User novo = new User();
        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jTextField_Email_Cadastro = new javax.swing.JTextField();
        jTextField_Nome_Cadastro = new javax.swing.JTextField();
        jLabel_Nome_Cadastro = new javax.swing.JLabel();
        jLabel_Email_Cadastro = new javax.swing.JLabel();
        jLabel_Cago = new javax.swing.JLabel();
        Combo_Cargo = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        label_Titulo = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(232, 231, 204));
        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel1.setPreferredSize(new java.awt.Dimension(1440, 1024));
        panel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                panel1ComponentResized(evt);
            }
        });

        jTextField_Email_Cadastro.setToolTipText("email");
        jTextField_Email_Cadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextField_Email_Cadastro.addActionListener(this::jTextField_Email_CadastroActionPerformed);

        jTextField_Nome_Cadastro.setToolTipText("email");
        jTextField_Nome_Cadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextField_Nome_Cadastro.addActionListener(this::jTextField_Nome_CadastroActionPerformed);

        jLabel_Nome_Cadastro.setBackground(new java.awt.Color(250, 166, 190));
        jLabel_Nome_Cadastro.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Nome_Cadastro.setForeground(new java.awt.Color(0, 90, 81));
        jLabel_Nome_Cadastro.setText("Nome:");

        jLabel_Email_Cadastro.setBackground(new java.awt.Color(250, 166, 190));
        jLabel_Email_Cadastro.setFont(new java.awt.Font("Sans Serif Collection", 0, 12)); // NOI18N
        jLabel_Email_Cadastro.setForeground(new java.awt.Color(0, 90, 81));
        jLabel_Email_Cadastro.setText("E-mail:");

        jLabel_Cago.setBackground(new java.awt.Color(250, 166, 190));
        jLabel_Cago.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Cago.setForeground(new java.awt.Color(0, 90, 81));
        jLabel_Cago.setText("Cargo:");

        Combo_Cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Administrador", "Auxiliar", " " }));
        Combo_Cargo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnCancelar.setForeground(new java.awt.Color(0, 90, 81));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnConfirmar.setBackground(new java.awt.Color(250, 166, 190));
        btnConfirmar.setForeground(new java.awt.Color(0, 90, 81));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setAutoscrolls(true);
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        label_Titulo.setAlignment(java.awt.Label.CENTER);
        label_Titulo.setBackground(new java.awt.Color(232, 231, 204));
        label_Titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label_Titulo.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        label_Titulo.setForeground(new java.awt.Color(0, 90, 81));
        label_Titulo.setText("Cadastrar Novo Usuário");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Nome_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Nome_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Email_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Email_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Cago, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnCancelar)
                        .addGap(59, 59, 59)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Combo_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(label_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel_Nome_Cadastro)
                .addGap(4, 4, 4)
                .addComponent(jTextField_Nome_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Email_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Email_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Cago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Combo_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnConfirmar))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Email_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Email_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Email_CadastroActionPerformed

    private void jTextField_Nome_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Nome_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Nome_CadastroActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void panel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panel1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_panel1ComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastrarUsuario2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combo_Cargo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel_Cago;
    private javax.swing.JLabel jLabel_Email_Cadastro;
    private javax.swing.JLabel jLabel_Nome_Cadastro;
    private javax.swing.JTextField jTextField_Email_Cadastro;
    private javax.swing.JTextField jTextField_Nome_Cadastro;
    private java.awt.Label label_Titulo;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
