/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author fanim
 */
public class ConfirmarAdocao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConfirmarAdocao.class.getName());

    /**
     * Creates new form ConfirmarAdocao
     */
    public ConfirmarAdocao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel_Adotante_Info = new javax.swing.JPanel();
        jLabel_Email_Adotante = new javax.swing.JLabel();
        jLabel_CPF_Adotante = new javax.swing.JLabel();
        jLabel101_Preferencias_Adotante = new javax.swing.JLabel();
        jLabel_Endereço_Adotante = new javax.swing.JLabel();
        jLabel_Tipo_Adotante = new javax.swing.JLabel();
        jLabel_Genero_Animal_Adotante = new javax.swing.JLabel();
        jLabel_Deficiencia_Animal_Adotante = new javax.swing.JLabel();
        jLabel_Porte__Animal_Adotante = new javax.swing.JLabel();
        jLabel_Chip__Animal_Adotante = new javax.swing.JLabel();
        jLabel_Cor__Animal_Adotante = new javax.swing.JLabel();
        jLabel_Nome_Adotante = new javax.swing.JLabel();
        jLabel_FIV__Animal_Adotante = new javax.swing.JLabel();
        jLabel_Castrado__Animal_Adotante = new javax.swing.JLabel();
        jLabel_FELV__Animal_Adotante = new javax.swing.JLabel();
        jButton_Editar = new javax.swing.JButton();
        edtCPF = new javax.swing.JLabel();
        edtEmail = new javax.swing.JLabel();
        edtEndereco = new javax.swing.JLabel();
        edtTipo = new javax.swing.JLabel();
        edtGenero = new javax.swing.JLabel();
        edtDeficiencia = new javax.swing.JLabel();
        edtPorte = new javax.swing.JLabel();
        edtChip = new javax.swing.JLabel();
        edtCor = new javax.swing.JLabel();
        edtCastrado = new javax.swing.JLabel();
        edtFELV = new javax.swing.JLabel();
        edtFIV = new javax.swing.JLabel();
        jButton1_Cancelar = new javax.swing.JButton();
        jButton2_Confirmar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel_Nome_Animal = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        label_tipo = new java.awt.Label();
        label_cor = new java.awt.Label();
        label_idade = new java.awt.Label();
        label_castrado = new java.awt.Label();
        label_genero = new java.awt.Label();
        label7 = new java.awt.Label();
        label_raca = new java.awt.Label();
        label_peso = new java.awt.Label();
        label_chip = new java.awt.Label();
        label_data_entrada = new java.awt.Label();
        label_deficiencia = new java.awt.Label();
        painelCabecalho = new javax.swing.JPanel();
        btnNotificacao = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtNomeUser = new javax.swing.JLabel();
        txtBemVindo = new javax.swing.JLabel();
        btnIcon = new javax.swing.JButton();
        txtFotoUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(232, 231, 204));
        jPanel3.setForeground(new java.awt.Color(0, 90, 81));

        jPanel_Adotante_Info.setBackground(new java.awt.Color(0, 90, 81));
        jPanel_Adotante_Info.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel_Adotante_Info.setForeground(new java.awt.Color(250, 166, 190));

        jLabel_Email_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Email_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Email_Adotante.setText("E-mail");
        jLabel_Email_Adotante.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel_Email_AdotanteComponentShown(evt);
            }
        });

        jLabel_CPF_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_CPF_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_CPF_Adotante.setText("CPF:");

        jLabel101_Preferencias_Adotante.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel101_Preferencias_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel101_Preferencias_Adotante.setText("Preferências:");

        jLabel_Endereço_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Endereço_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Endereço_Adotante.setText("Endereço:");

        jLabel_Tipo_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Tipo_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Tipo_Adotante.setText("Tipo:");

        jLabel_Genero_Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Genero_Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Genero_Animal_Adotante.setText("Gênero:");

        jLabel_Deficiencia_Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Deficiencia_Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Deficiencia_Animal_Adotante.setText("Deficiência:");

        jLabel_Porte__Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Porte__Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Porte__Animal_Adotante.setText("Porte:");

        jLabel_Chip__Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Chip__Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Chip__Animal_Adotante.setText("Chip:");

        jLabel_Cor__Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Cor__Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Cor__Animal_Adotante.setText("Cor:");

        jLabel_Nome_Adotante.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel_Nome_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Nome_Adotante.setText("Nome adotante");

        jLabel_FIV__Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_FIV__Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_FIV__Animal_Adotante.setText("FIV:");

        jLabel_Castrado__Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Castrado__Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Castrado__Animal_Adotante.setText("Castrado:");

        jLabel_FELV__Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_FELV__Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_FELV__Animal_Adotante.setText("FELV:");

        jButton_Editar.setBackground(new java.awt.Color(0, 90, 81));
        jButton_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jButton_Editar.setBorder(null);

        edtCPF.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        edtCPF.setForeground(new java.awt.Color(250, 166, 190));
        edtCPF.setText("jLabel2");

        edtEmail.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        edtEmail.setForeground(new java.awt.Color(250, 166, 190));
        edtEmail.setText("jLabel2");

        edtEndereco.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        edtEndereco.setForeground(new java.awt.Color(250, 166, 190));
        edtEndereco.setText("jLabel2");

        edtTipo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        edtTipo.setForeground(new java.awt.Color(250, 166, 190));
        edtTipo.setText("jLabel2");

        edtGenero.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        edtGenero.setForeground(new java.awt.Color(250, 166, 190));
        edtGenero.setText("jLabel2");

        edtDeficiencia.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        edtDeficiencia.setForeground(new java.awt.Color(250, 166, 190));
        edtDeficiencia.setText("jLabel2");

        edtPorte.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        edtPorte.setForeground(new java.awt.Color(250, 166, 190));
        edtPorte.setText("jLabel2");

        edtChip.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        edtChip.setForeground(new java.awt.Color(250, 166, 190));
        edtChip.setText("jLabel2");

        edtCor.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        edtCor.setForeground(new java.awt.Color(250, 166, 190));
        edtCor.setText("jLabel2");

        edtCastrado.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        edtCastrado.setForeground(new java.awt.Color(250, 166, 190));
        edtCastrado.setText("jLabel2");

        edtFELV.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        edtFELV.setForeground(new java.awt.Color(250, 166, 190));
        edtFELV.setText("jLabel2");

        edtFIV.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        edtFIV.setForeground(new java.awt.Color(250, 166, 190));
        edtFIV.setText("jLabel2");

        javax.swing.GroupLayout jPanel_Adotante_InfoLayout = new javax.swing.GroupLayout(jPanel_Adotante_Info);
        jPanel_Adotante_Info.setLayout(jPanel_Adotante_InfoLayout);
        jPanel_Adotante_InfoLayout.setHorizontalGroup(
            jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Adotante_InfoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Editar))
                    .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                        .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Nome_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addComponent(jLabel_Porte__Animal_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtPorte, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addComponent(jLabel_Tipo_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel101_Preferencias_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addComponent(jLabel_CPF_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Email_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Endereço_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addComponent(jLabel_Deficiencia_Animal_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtDeficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addComponent(jLabel_Genero_Animal_Adotante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_Chip__Animal_Adotante, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                    .addComponent(jLabel_Cor__Animal_Adotante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtChip, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addComponent(jLabel_Castrado__Animal_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtCastrado, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addComponent(jLabel_FIV__Animal_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtFIV, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addComponent(jLabel_FELV__Animal_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtFELV, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_Adotante_InfoLayout.setVerticalGroup(
            jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Editar)
                .addGap(16, 16, 16)
                .addComponent(jLabel_Nome_Adotante)
                .addGap(18, 18, 18)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CPF_Adotante)
                    .addComponent(edtCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Email_Adotante)
                    .addComponent(edtEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Endereço_Adotante)
                    .addComponent(edtEndereco))
                .addGap(56, 56, 56)
                .addComponent(jLabel101_Preferencias_Adotante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Tipo_Adotante)
                    .addComponent(edtTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Genero_Animal_Adotante)
                    .addComponent(edtGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Deficiencia_Animal_Adotante)
                    .addComponent(edtDeficiencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Porte__Animal_Adotante)
                    .addComponent(edtPorte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Chip__Animal_Adotante)
                    .addComponent(edtChip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Cor__Animal_Adotante)
                    .addComponent(edtCor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Castrado__Animal_Adotante)
                    .addComponent(edtCastrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_FIV__Animal_Adotante)
                    .addComponent(edtFIV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtFELV)
                    .addComponent(jLabel_FELV__Animal_Adotante))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jButton1_Cancelar.setBackground(new java.awt.Color(255, 253, 208));
        jButton1_Cancelar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton1_Cancelar.setForeground(new java.awt.Color(0, 90, 81));
        jButton1_Cancelar.setText("Cancelar");

        jButton2_Confirmar1.setBackground(new java.awt.Color(250, 166, 190));
        jButton2_Confirmar1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton2_Confirmar1.setForeground(new java.awt.Color(0, 90, 81));
        jButton2_Confirmar1.setText("Confirmar");
        jButton2_Confirmar1.addActionListener(this::jButton2_Confirmar1ActionPerformed);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 90, 81));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Processo de Adoção:");

        jPanel2.setBackground(new java.awt.Color(0, 90, 81));
        jPanel2.setPreferredSize(new java.awt.Dimension(232, 418));

        jLabel57.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(250, 166, 190));
        jLabel57.setText("Castrado:");

        jLabel54.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(250, 166, 190));
        jLabel54.setText("Idade:");

        jLabel53.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(250, 166, 190));
        jLabel53.setText("Genêro:");

        jLabel58.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(250, 166, 190));
        jLabel58.setText("Peso:");

        jLabel_Nome_Animal.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel_Nome_Animal.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Nome_Animal.setText("Nome animal");

        jLabel59.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(250, 166, 190));
        jLabel59.setText("Chip:");

        jLabel52.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(250, 166, 190));
        jLabel52.setText("Tipo:");

        jLabel55.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(250, 166, 190));
        jLabel55.setText("Raça:");

        jLabel51.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(250, 166, 190));
        jLabel51.setText("Cor:");
        jLabel51.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel51ComponentShown(evt);
            }
        });

        jLabel60.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(250, 166, 190));
        jLabel60.setText("Data_entrada:");

        jLabel56.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(250, 166, 190));
        jLabel56.setText("Deficiência:");

        jPanel17.setBackground(new java.awt.Color(232, 231, 204));
        jPanel17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel62)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        label_tipo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        label_tipo.setForeground(new java.awt.Color(250, 166, 190));
        label_tipo.setText("label1");

        label_cor.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        label_cor.setForeground(new java.awt.Color(250, 166, 190));
        label_cor.setText("label1");

        label_idade.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        label_idade.setForeground(new java.awt.Color(250, 166, 190));
        label_idade.setText("label1");

        label_castrado.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        label_castrado.setForeground(new java.awt.Color(250, 166, 190));
        label_castrado.setText("label1");

        label_genero.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        label_genero.setForeground(new java.awt.Color(250, 166, 190));
        label_genero.setText("label1");

        label7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        label7.setForeground(new java.awt.Color(250, 166, 190));
        label7.setText("label1");

        label_raca.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        label_raca.setForeground(new java.awt.Color(250, 166, 190));
        label_raca.setText("label1");

        label_peso.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        label_peso.setForeground(new java.awt.Color(250, 166, 190));
        label_peso.setText("label1");

        label_chip.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        label_chip.setForeground(new java.awt.Color(250, 166, 190));
        label_chip.setText("label1");

        label_data_entrada.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        label_data_entrada.setForeground(new java.awt.Color(250, 166, 190));
        label_data_entrada.setText("label1");

        label_deficiencia.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        label_deficiencia.setForeground(new java.awt.Color(250, 166, 190));
        label_deficiencia.setText("label1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel_Nome_Animal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(label_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(label_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_deficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_raca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(label_data_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(label_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_chip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_castrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Nome_Animal)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addComponent(label_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51)
                    .addComponent(label_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel54)
                    .addComponent(label_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(label_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel53))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel55))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_raca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel56)
                    .addComponent(label_deficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57)
                    .addComponent(label_castrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58)
                    .addComponent(label_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel59)
                    .addComponent(label_chip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel60)
                    .addComponent(label_data_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(684, 684, 684)
                .addComponent(jButton1_Cancelar)
                .addGap(94, 94, 94)
                .addComponent(jButton2_Confirmar1)
                .addGap(381, 599, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(465, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184)
                .addComponent(jPanel_Adotante_Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(403, 403, 403))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addComponent(jPanel_Adotante_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_Cancelar)
                    .addComponent(jButton2_Confirmar1))
                .addContainerGap(282, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1542, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelCabecalho.setBackground(new java.awt.Color(0, 90, 81));
        painelCabecalho.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        painelCabecalho.setForeground(new java.awt.Color(0, 90, 81));
        painelCabecalho.setEnabled(false);

        btnNotificacao.setBackground(new java.awt.Color(0, 90, 81));
        btnNotificacao.setForeground(new java.awt.Color(0, 90, 81));
        btnNotificacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/notificacao.png"))); // NOI18N
        btnNotificacao.setBorder(null);
        btnNotificacao.addActionListener(this::btnNotificacaoActionPerformed);

        jPanel4.setBackground(new java.awt.Color(0, 90, 81));

        txtNomeUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtNomeUser.setForeground(new java.awt.Color(250, 166, 190));
        txtNomeUser.setText("ADM     XXXX");
        txtNomeUser.setToolTipText("");
        txtNomeUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtBemVindo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtBemVindo.setForeground(new java.awt.Color(232, 231, 204));
        txtBemVindo.setText("Bem vindo!!");
        txtBemVindo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtNomeUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNomeUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBemVindo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIcon.setBackground(new java.awt.Color(0, 90, 81));
        btnIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_acolhepet.png"))); // NOI18N
        btnIcon.setBorder(null);
        btnIcon.addActionListener(this::btnIconActionPerformed);

        txtFotoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_user.png"))); // NOI18N

        javax.swing.GroupLayout painelCabecalhoLayout = new javax.swing.GroupLayout(painelCabecalho);
        painelCabecalho.setLayout(painelCabecalhoLayout);
        painelCabecalhoLayout.setHorizontalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCabecalhoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFotoUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNotificacao)
                .addGap(24, 24, 24))
        );
        painelCabecalhoLayout.setVerticalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(txtFotoUser)
                .addGroup(painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCabecalhoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnNotificacao))
                    .addGroup(painelCabecalhoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(btnIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(painelCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_Email_AdotanteComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel_Email_AdotanteComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Email_AdotanteComponentShown

    private void jButton2_Confirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_Confirmar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2_Confirmar1ActionPerformed

    private void jLabel51ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel51ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel51ComponentShown

    private void btnNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNotificacaoActionPerformed

    private void btnIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConfirmarAdocao().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIcon;
    private javax.swing.JButton btnNotificacao;
    private javax.swing.JLabel edtCPF;
    private javax.swing.JLabel edtCastrado;
    private javax.swing.JLabel edtChip;
    private javax.swing.JLabel edtCor;
    private javax.swing.JLabel edtDeficiencia;
    private javax.swing.JLabel edtEmail;
    private javax.swing.JLabel edtEndereco;
    private javax.swing.JLabel edtFELV;
    private javax.swing.JLabel edtFIV;
    private javax.swing.JLabel edtGenero;
    private javax.swing.JLabel edtPorte;
    private javax.swing.JLabel edtTipo;
    private javax.swing.JButton jButton1_Cancelar;
    private javax.swing.JButton jButton2_Confirmar1;
    private javax.swing.JButton jButton_Editar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel101_Preferencias_Adotante;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel_CPF_Adotante;
    private javax.swing.JLabel jLabel_Castrado__Animal_Adotante;
    private javax.swing.JLabel jLabel_Chip__Animal_Adotante;
    private javax.swing.JLabel jLabel_Cor__Animal_Adotante;
    private javax.swing.JLabel jLabel_Deficiencia_Animal_Adotante;
    private javax.swing.JLabel jLabel_Email_Adotante;
    private javax.swing.JLabel jLabel_Endereço_Adotante;
    private javax.swing.JLabel jLabel_FELV__Animal_Adotante;
    private javax.swing.JLabel jLabel_FIV__Animal_Adotante;
    private javax.swing.JLabel jLabel_Genero_Animal_Adotante;
    private javax.swing.JLabel jLabel_Nome_Adotante;
    private javax.swing.JLabel jLabel_Nome_Animal;
    private javax.swing.JLabel jLabel_Porte__Animal_Adotante;
    private javax.swing.JLabel jLabel_Tipo_Adotante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_Adotante_Info;
    private java.awt.Label label7;
    private java.awt.Label label_castrado;
    private java.awt.Label label_chip;
    private java.awt.Label label_cor;
    private java.awt.Label label_data_entrada;
    private java.awt.Label label_deficiencia;
    private java.awt.Label label_genero;
    private java.awt.Label label_idade;
    private java.awt.Label label_peso;
    private java.awt.Label label_raca;
    private java.awt.Label label_tipo;
    private javax.swing.JPanel painelCabecalho;
    private javax.swing.JLabel txtBemVindo;
    private javax.swing.JLabel txtFotoUser;
    private javax.swing.JLabel txtNomeUser;
    // End of variables declaration//GEN-END:variables
}
