/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.SistemaController;
import Model_Entety.Adocao;
import Model_Entety.Adotante;
import Model_Entety.Animal;
import Model_Entety.Preferencias;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import service.FotoService;

public class ConfirmarAdocao extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConfirmarAdocao.class.getName());

    private Animal animal;
    private Adotante adotante;
    private String cpf;
    private JFrame main;

    public ConfirmarAdocao() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    public ConfirmarAdocao(Animal animal, String cpf, JFrame main) {
        initComponents();
        this.cpf = cpf;
        this.animal = animal;
        this.main = main;
        carregar(animal, cpf);
    }

    private void carregar(Animal animal, String cpf) {

        try {
            FotoService fotoService = new FotoService();
            SistemaController sc = new SistemaController();
            adotante = sc.buscarPorCpf(cpf);

            System.out.println(adotante.getId());
            System.out.println(adotante.getNome());
            edtipoA.setText(animal.getTipo());
            edcorA.setText(animal.getCor());
            edidadeA.setText(String.valueOf(animal.getIdade()));
            edgeneroA.setText(String.valueOf(animal.getGenero()));
            edracaA.setText(animal.getRaca());

            eddificienciaA.setText(
                    animal.isDeficiencia()
                    ? "Sim"
                    : "Não"
            );

            edcastradoA.setText(
                    animal.isCastrado()
                    ? "Sim"
                    : "Não"
            );

            edpesoA.setText(
                    String.valueOf(animal.getPeso())
            );

            eddata.setText(
                    animal.getDataEntrada() == null
                    ? ""
                    : animal.getDataEntrada().toString()
            );

            img.setIcon(
                    fotoService.render(
                            animal.getFoto(),
                            img.getWidth(),
                            img.getHeight()
                    )
            );

            jLabel_Nome_Adotante.setText(adotante.getNome());
            edtCPF.setText(adotante.getCpf());
            edtEmail.setText(adotante.getEmail());
            edtEndereco.setText(adotante.getEndereco());
            SistemaController c = new SistemaController();

            Preferencias p = c.buscarPreferencias(adotante.getId());

            if (p != null) {

                edtTipo.setText(p.getTipo());
                edtCor.setText(p.getCor());
                System.out.println("--------------------------");
                System.out.println(p.getCor());
                System.out.println(p.getGenero());
                edtGenero.setText(
                        p.getGenero() == '\0'
                        ? ""
                        : String.valueOf(p.getGenero())
                );

                edtPorte.setText(
                        p.getPorte() == '\0'
                        ? ""
                        : String.valueOf(p.getPorte())
                );

                edtDeficiencia.setText(
                        p.isDeficiencia()
                        ? "Sim"
                        : "Não"
                );

                edtCastrado.setText(
                        p.isCastrado()
                        ? "Sim"
                        : "Não"
                );

                edtFIV.setText(
                        p.isFIV()
                        ? "Aceita"
                        : "Não aceita"
                );

                edtFELV.setText(
                        p.isFELV()
                        ? "Aceita"
                        : "Não aceita"
                );
            }
        } catch (SQLException ex) {
            System.getLogger(ConfirmarAdocao.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel_Adotante_Info = new javax.swing.JPanel();
        jLabel_Email_Adotante = new javax.swing.JLabel();
        jLabel_CPF_Adotante = new javax.swing.JLabel();
        jLabel101_Preferencias_Adotante = new javax.swing.JLabel();
        jLabel_Endereço_Adotante = new javax.swing.JLabel();
        jLabel_Tipo_Adotante = new javax.swing.JLabel();
        jLabel_Genero_Animal_Adotante = new javax.swing.JLabel();
        jLabel_Deficiencia_Animal_Adotante = new javax.swing.JLabel();
        jLabel_Porte__Animal_Adotante = new javax.swing.JLabel();
        jLabel_Chip__Animal_Adotante = new javax.swing.JLabel();
        jLabel_Cor__Animal_Adotante = new javax.swing.JLabel();
        jLabel_Nome_Adotante = new javax.swing.JLabel();
        jLabel_FIV__Animal_Adotante = new javax.swing.JLabel();
        jLabel_Castrado__Animal_Adotante = new javax.swing.JLabel();
        jLabel_FELV__Animal_Adotante = new javax.swing.JLabel();
        edtCPF = new javax.swing.JLabel();
        edtEmail = new javax.swing.JLabel();
        edtEndereco = new javax.swing.JLabel();
        edtTipo = new javax.swing.JLabel();
        edtGenero = new javax.swing.JLabel();
        edtDeficiencia = new javax.swing.JLabel();
        edtPorte = new javax.swing.JLabel();
        edtCor = new javax.swing.JLabel();
        edtCastrado = new javax.swing.JLabel();
        edtFELV = new javax.swing.JLabel();
        edtFIV = new javax.swing.JLabel();
        jButton1_Cancelar = new javax.swing.JButton();
        jButton2_Confirmar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel_Nome_Animal = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        edtipoA = new javax.swing.JLabel();
        edcorA = new javax.swing.JLabel();
        edidadeA = new javax.swing.JLabel();
        edgeneroA = new javax.swing.JLabel();
        edracaA = new javax.swing.JLabel();
        eddificienciaA = new javax.swing.JLabel();
        edcastradoA = new javax.swing.JLabel();
        edpesoA = new javax.swing.JLabel();
        eddata = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        painelCabecalho = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(232, 231, 204));
        jPanel3.setForeground(new java.awt.Color(0, 90, 81));

        jPanel_Adotante_Info.setBackground(new java.awt.Color(0, 90, 81));
        jPanel_Adotante_Info.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel_Adotante_Info.setForeground(new java.awt.Color(250, 166, 190));

        jLabel_Email_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Email_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Email_Adotante.setText("E-mail");
        jLabel_Email_Adotante.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel_Email_AdotanteComponentShown(evt);
            }
        });

        jLabel_CPF_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_CPF_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_CPF_Adotante.setText("CPF:");

        jLabel101_Preferencias_Adotante.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel101_Preferencias_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel101_Preferencias_Adotante.setText("Preferências:");

        jLabel_Endereço_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Endereço_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Endereço_Adotante.setText("Endereço:");

        jLabel_Tipo_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Tipo_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Tipo_Adotante.setText("Tipo:");

        jLabel_Genero_Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Genero_Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Genero_Animal_Adotante.setText("Gênero:");

        jLabel_Deficiencia_Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Deficiencia_Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Deficiencia_Animal_Adotante.setText("Deficiência:");

        jLabel_Porte__Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Porte__Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Porte__Animal_Adotante.setText("Porte:");

        jLabel_Chip__Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Chip__Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));

        jLabel_Cor__Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Cor__Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Cor__Animal_Adotante.setText("Cor:");

        jLabel_Nome_Adotante.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel_Nome_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Nome_Adotante.setText("Nome adotante");

        jLabel_FIV__Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_FIV__Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_FIV__Animal_Adotante.setText("FIV:");

        jLabel_Castrado__Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_Castrado__Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Castrado__Animal_Adotante.setText("Castrado:");

        jLabel_FELV__Animal_Adotante.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel_FELV__Animal_Adotante.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_FELV__Animal_Adotante.setText("FELV:");

        edtCPF.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        edtCPF.setForeground(new java.awt.Color(250, 166, 190));
        edtCPF.setText("jLabel2");

        edtEmail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        edtEmail.setForeground(new java.awt.Color(250, 166, 190));
        edtEmail.setText("jLabel2");

        edtEndereco.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        edtEndereco.setForeground(new java.awt.Color(250, 166, 190));
        edtEndereco.setText("jLabel2");

        edtTipo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        edtTipo.setForeground(new java.awt.Color(250, 166, 190));
        edtTipo.setText("jLabel2");

        edtGenero.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        edtGenero.setForeground(new java.awt.Color(250, 166, 190));
        edtGenero.setText("jLabel2");

        edtDeficiencia.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        edtDeficiencia.setForeground(new java.awt.Color(250, 166, 190));
        edtDeficiencia.setText("jLabel2");

        edtPorte.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        edtPorte.setForeground(new java.awt.Color(250, 166, 190));
        edtPorte.setText("jLabel2");

        edtCor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        edtCor.setForeground(new java.awt.Color(250, 166, 190));
        edtCor.setText("jLabel2");

        edtCastrado.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        edtCastrado.setForeground(new java.awt.Color(250, 166, 190));
        edtCastrado.setText("jLabel2");

        edtFELV.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        edtFELV.setForeground(new java.awt.Color(250, 166, 190));
        edtFELV.setText("jLabel2");

        edtFIV.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        edtFIV.setForeground(new java.awt.Color(250, 166, 190));
        edtFIV.setText("jLabel2");

        javax.swing.GroupLayout jPanel_Adotante_InfoLayout = new javax.swing.GroupLayout(jPanel_Adotante_Info);
        jPanel_Adotante_Info.setLayout(jPanel_Adotante_InfoLayout);
        jPanel_Adotante_InfoLayout.setHorizontalGroup(
            jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                        .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addComponent(jLabel_Genero_Animal_Adotante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addComponent(jLabel_Porte__Animal_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtPorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_Chip__Animal_Adotante, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                    .addComponent(jLabel_Cor__Animal_Adotante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtCor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addComponent(jLabel_Castrado__Animal_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtCastrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addComponent(jLabel_FIV__Animal_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtFIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addComponent(jLabel_FELV__Animal_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtFELV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Nome_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                        .addComponent(jLabel_Tipo_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(edtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addComponent(jLabel_Deficiencia_Animal_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtDeficiencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                        .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel101_Preferencias_Adotante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addComponent(jLabel_CPF_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edtCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Email_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Endereço_Adotante, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                                        .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 8, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        jPanel_Adotante_InfoLayout.setVerticalGroup(
            jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Adotante_InfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Nome_Adotante)
                .addGap(18, 18, 18)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CPF_Adotante)
                    .addComponent(edtCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Email_Adotante)
                    .addComponent(edtEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Endereço_Adotante)
                    .addComponent(edtEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel101_Preferencias_Adotante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Tipo_Adotante)
                    .addComponent(edtTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Genero_Animal_Adotante)
                    .addComponent(edtGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Deficiencia_Animal_Adotante)
                    .addComponent(edtDeficiencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Porte__Animal_Adotante)
                    .addComponent(edtPorte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Chip__Animal_Adotante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Cor__Animal_Adotante)
                    .addComponent(edtCor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Castrado__Animal_Adotante)
                    .addComponent(edtCastrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_FIV__Animal_Adotante)
                    .addComponent(edtFIV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Adotante_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtFELV)
                    .addComponent(jLabel_FELV__Animal_Adotante))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jButton1_Cancelar.setBackground(new java.awt.Color(255, 253, 208));
        jButton1_Cancelar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton1_Cancelar.setForeground(new java.awt.Color(0, 90, 81));
        jButton1_Cancelar.setText("Cancelar");
        jButton1_Cancelar.addActionListener(this::jButton1_CancelarActionPerformed);

        jButton2_Confirmar1.setBackground(new java.awt.Color(250, 166, 190));
        jButton2_Confirmar1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton2_Confirmar1.setForeground(new java.awt.Color(0, 90, 81));
        jButton2_Confirmar1.setText("Confirmar");
        jButton2_Confirmar1.addActionListener(this::jButton2_Confirmar1ActionPerformed);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 90, 81));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Processo de Adoção:");

        jPanel4.setBackground(new java.awt.Color(0, 90, 81));
        jPanel4.setPreferredSize(new java.awt.Dimension(232, 418));

        jLabel57.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(250, 166, 190));
        jLabel57.setText("Castrado:");

        jLabel54.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(250, 166, 190));
        jLabel54.setText("Idade:");

        jLabel53.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(250, 166, 190));
        jLabel53.setText("Genêro:");

        jLabel58.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(250, 166, 190));
        jLabel58.setText("Peso:");

        jLabel_Nome_Animal.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel_Nome_Animal.setForeground(new java.awt.Color(250, 166, 190));
        jLabel_Nome_Animal.setText("Nome animal");

        jLabel52.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(250, 166, 190));
        jLabel52.setText("Tipo:");

        jLabel55.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(250, 166, 190));
        jLabel55.setText("Raça:");

        jLabel51.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(250, 166, 190));
        jLabel51.setText("Cor:");
        jLabel51.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel51ComponentShown(evt);
            }
        });

        jLabel60.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(250, 166, 190));
        jLabel60.setText("Data_entrada:");

        jLabel56.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(250, 166, 190));
        jLabel56.setText("Deficiência:");

        edtipoA.setText("jLabel1");

        edcorA.setText("jLabel1");

        edidadeA.setText("jLabel1");

        edgeneroA.setText("jLabel1");

        edracaA.setText("jLabel1");

        eddificienciaA.setText("jLabel1");

        edcastradoA.setText("jLabel1");

        edpesoA.setText("jLabel1");

        eddata.setText("jLabel1");

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagem.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(img))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel_Nome_Animal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(edracaA))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(edgeneroA))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eddificienciaA)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtipoA))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edcorA))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edpesoA))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edidadeA))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edcastradoA))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eddata)))))
                .addGap(53, 53, 53))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(img)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Nome_Animal)
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(edtipoA))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(edcorA))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(edidadeA))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(edgeneroA))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(edracaA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(eddificienciaA))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(edcastradoA))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(edpesoA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(eddata))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(jPanel_Adotante_Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jButton1_Cancelar)
                .addGap(47, 47, 47)
                .addComponent(jButton2_Confirmar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel_Adotante_Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_Cancelar)
                    .addComponent(jButton2_Confirmar1))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelCabecalho.setBackground(new java.awt.Color(0, 90, 81));
        painelCabecalho.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        painelCabecalho.setForeground(new java.awt.Color(0, 90, 81));
        painelCabecalho.setEnabled(false);

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_acolhepet.png"))); // NOI18N
        icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelCabecalhoLayout = new javax.swing.GroupLayout(painelCabecalho);
        painelCabecalho.setLayout(painelCabecalhoLayout);
        painelCabecalhoLayout.setHorizontalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCabecalhoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(icon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCabecalhoLayout.setVerticalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(painelCabecalhoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(icon))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(painelCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_Email_AdotanteComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel_Email_AdotanteComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Email_AdotanteComponentShown

    private void jButton2_Confirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_Confirmar1ActionPerformed
        try{
            SistemaController s = new SistemaController();
            Adocao ad = new Adocao();
            ad.setAdotanteId(adotante.getId());
            ad.setAnimalId(animal.getId());
            ad.setStatus("Concluída");
            ad.setObservacao(""); 
            s.salvarAdocao(ad);

            
            s.atualizarStatus(animal.getId(), "Adotado");

          
            Model_Entety.Historico hist = new Model_Entety.Historico();
            hist.setAdotanteId(adotante.getId());
            hist.setAnimalId(animal.getId());
            hist.setAcao("Adoção de: " + animal.getNome());
            s.salvarHistorico(hist);

            JOptionPane.showMessageDialog(this, "Adoção realizada com sucesso!");

         
            Main m = new Main();
            m.setVisible(true);
            this.dispose();
            if (main != null) main.dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao realizar adoção: " + ex.getMessage());
            logger.log(java.util.logging.Level.SEVERE, "Erro", ex);

        }

    }//GEN-LAST:event_jButton2_Confirmar1ActionPerformed

    private void jLabel51ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel51ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel51ComponentShown

    private void iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMouseClicked
        Main m = new  Main();
        this.dispose();
        m.setVisible(true);
    }//GEN-LAST:event_iconMouseClicked

    private void jButton1_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_CancelarActionPerformed
        Main m = new  Main();
        this.dispose();
        m.setVisible(true);
    }//GEN-LAST:event_jButton1_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConfirmarAdocao().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel edcastradoA;
    private javax.swing.JLabel edcorA;
    private javax.swing.JLabel eddata;
    private javax.swing.JLabel eddificienciaA;
    private javax.swing.JLabel edgeneroA;
    private javax.swing.JLabel edidadeA;
    private javax.swing.JLabel edpesoA;
    private javax.swing.JLabel edracaA;
    private javax.swing.JLabel edtCPF;
    private javax.swing.JLabel edtCastrado;
    private javax.swing.JLabel edtCor;
    private javax.swing.JLabel edtDeficiencia;
    private javax.swing.JLabel edtEmail;
    private javax.swing.JLabel edtEndereco;
    private javax.swing.JLabel edtFELV;
    private javax.swing.JLabel edtFIV;
    private javax.swing.JLabel edtGenero;
    private javax.swing.JLabel edtPorte;
    private javax.swing.JLabel edtTipo;
    private javax.swing.JLabel edtipoA;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1_Cancelar;
    private javax.swing.JButton jButton2_Confirmar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel101_Preferencias_Adotante;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel_CPF_Adotante;
    private javax.swing.JLabel jLabel_Castrado__Animal_Adotante;
    private javax.swing.JLabel jLabel_Chip__Animal_Adotante;
    private javax.swing.JLabel jLabel_Cor__Animal_Adotante;
    private javax.swing.JLabel jLabel_Deficiencia_Animal_Adotante;
    private javax.swing.JLabel jLabel_Email_Adotante;
    private javax.swing.JLabel jLabel_Endereço_Adotante;
    private javax.swing.JLabel jLabel_FELV__Animal_Adotante;
    private javax.swing.JLabel jLabel_FIV__Animal_Adotante;
    private javax.swing.JLabel jLabel_Genero_Animal_Adotante;
    private javax.swing.JLabel jLabel_Nome_Adotante;
    private javax.swing.JLabel jLabel_Nome_Animal;
    private javax.swing.JLabel jLabel_Porte__Animal_Adotante;
    private javax.swing.JLabel jLabel_Tipo_Adotante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_Adotante_Info;
    private javax.swing.JPanel painelCabecalho;
    // End of variables declaration//GEN-END:variables


}
