/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;
import Model_Entety.Historico;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author danie
 */
public class HistoricoItemPanel extends javax.swing.JPanel {
    // Usando os JLabels que você já criou no Design do NetBeans
    public HistoricoItemPanel(Historico h) {
        initComponents();
        carregar(h);
    }

    public void carregar(Historico h) {
        
        txtStatusAnimal.setText("Ação: " + h.getAcao()); 
        txtIdAnimal.setText("Animal ID: " + h.getAnimalId());

        if (h.getDataEvento() != null) {
            txtDataAnimal.setText("Data: " + h.getDataEvento().toLocalDate().toString());
        }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNomeAnimal = new javax.swing.JLabel();
        txtIdAnimal = new javax.swing.JLabel();
        txtStatusAnimal = new javax.swing.JLabel();
        txtDataAnimal = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 90, 81));
        jLabel2.setText("Nome Animal");

        setBackground(new java.awt.Color(232, 231, 204));

        txtNomeAnimal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtNomeAnimal.setForeground(new java.awt.Color(0, 90, 81));
        txtNomeAnimal.setText("Nome Animal");

        txtIdAnimal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtIdAnimal.setForeground(new java.awt.Color(0, 90, 81));
        txtIdAnimal.setText("Id Animal");

        txtStatusAnimal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtStatusAnimal.setForeground(new java.awt.Color(0, 90, 81));
        txtStatusAnimal.setText("Status");

        txtDataAnimal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtDataAnimal.setForeground(new java.awt.Color(0, 90, 81));
        txtDataAnimal.setText("Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txtNomeAnimal)
                .addGap(18, 18, 18)
                .addComponent(txtIdAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(txtStatusAnimal)
                .addGap(18, 18, 18)
                .addComponent(txtDataAnimal)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeAnimal)
                    .addComponent(txtIdAnimal)
                    .addComponent(txtStatusAnimal)
                    .addComponent(txtDataAnimal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtDataAnimal;
    private javax.swing.JLabel txtIdAnimal;
    private javax.swing.JLabel txtNomeAnimal;
    private javax.swing.JLabel txtStatusAnimal;
    // End of variables declaration//GEN-END:variables
}
