/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.SistemaController;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class ItemVacina extends javax.swing.JPanel {

    /**
     * Creates new form Vacina
     */
    private int idVacina;


    public ItemVacina() {
        initComponents();
    }
    public void setDados(String nome, String id) {
        this.idVacina = Integer.parseInt(id); 
        txtNomeVacina.setText("Nome Vacina: " + nome);
        txtIdVacina.setText("ID: " + id);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomeVacina = new javax.swing.JLabel();
        txtIdVacina = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(232, 231, 204));

        txtNomeVacina.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtNomeVacina.setForeground(new java.awt.Color(0, 90, 81));
        txtNomeVacina.setText("Nome Vacina: ");

        txtIdVacina.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtIdVacina.setForeground(new java.awt.Color(0, 90, 81));
        txtIdVacina.setText("Id Vacina:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-editar-24.png"))); // NOI18N
        jLabel1.setToolTipText("Editar Vacina");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtNomeVacina, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdVacina, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdVacina)
                        .addComponent(txtNomeVacina))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        Model_Entety.Vacina v = new Model_Entety.Vacina();
        v.setId(this.idVacina); 
        v.setNome(txtNomeVacina.getText().replace("Nome Vacina: ", ""));

        CadastrarVacinas tela = new CadastrarVacinas(v);
        tela.setVisible(true);
        java.awt.Window janelaPai = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (janelaPai != null) {
            janelaPai.dispose();
        }
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtIdVacina;
    private javax.swing.JLabel txtNomeVacina;
    // End of variables declaration//GEN-END:variables
}
