/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Dao.UserDAO;
import Model_Entety.User;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class ItemUsuarioCadastrado extends javax.swing.JPanel {

    private User user;

    
    public ItemUsuarioCadastrado() {
        initComponents();
    }
    public ItemUsuarioCadastrado(User user) {
        initComponents();
        
        this.user = user;
        
        txtNome.setText("Nome: " + user.getNome());
        txtEmail.setText("E-mail: " + user.getEmail());
        txtTipo.setText("Cargo: " + user.getTipo());
        if(user.isAtivo()==true){
           txtStatus.setText("Status: Ativo");
        }else{
           txtStatus.setText("Status: Inativo");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTipo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        iconApagar = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtTipo = new javax.swing.JLabel();
        iconEditar = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();

        txtTipo1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtTipo1.setForeground(new java.awt.Color(0, 90, 81));
        txtTipo1.setText("Cargo:");

        jPanel1.setBackground(new java.awt.Color(232, 231, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 151));

        iconApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-lixeira-24.png"))); // NOI18N
        iconApagar.setToolTipText("Apagar Usuário");
        iconApagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconApagarMouseClicked(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(0, 90, 81));
        txtNome.setText("Nome:");

        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 90, 81));
        txtEmail.setText("E-mail:");

        txtTipo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(0, 90, 81));
        txtTipo.setText("Cargo:");

        iconEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-editar-24.png"))); // NOI18N
        iconEditar.setToolTipText("Editar Usuário");
        iconEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconEditarMouseClicked(evt);
            }
        });

        txtStatus.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(0, 90, 81));
        txtStatus.setText("Cargo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(iconApagar)
                .addGap(18, 18, 18)
                .addComponent(iconEditar)
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTipo)
                    .addComponent(txtEmail)
                    .addComponent(txtNome)
                    .addComponent(txtStatus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconEditar)
                    .addComponent(iconApagar))
                .addGap(15, 15, 15)
                .addComponent(txtNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void iconApagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconApagarMouseClicked
        int resposta = JOptionPane.showConfirmDialog(null, 
            "Tem certeza que deseja excluir o usuário " + user.getNome() + "?", 
            "Confirmação", JOptionPane.YES_NO_OPTION);

    if (resposta == JOptionPane.YES_OPTION) {
        try {
            // Chama o DAO diretamente ou via Controller
            Dao.UserDAO dao = new Dao.UserDAO();
            dao.deletar(user.getId());
            
            JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso!");
            
            // Remove o painel da tela visualmente
            this.setVisible(false);
            this.getParent().remove(this);
            this.getParent().revalidate();
            this.getParent().repaint();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_iconApagarMouseClicked

    private void iconEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconEditarMouseClicked
        CadastrarUsuario tela = new CadastrarUsuario(this.user);
        tela.setVisible(true);
        java.awt.Window janelaPai = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (janelaPai != null) {
            janelaPai.dispose();
        }
        
    }//GEN-LAST:event_iconEditarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconApagar;
    private javax.swing.JLabel iconEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JLabel txtTipo;
    private javax.swing.JLabel txtTipo1;
    // End of variables declaration//GEN-END:variables
}
